# Site settings

title: Les communs
email: contact@encommuns.org
description: > # this means to ignore newlines until "baseurl:"
  Repérer les communs et les caractériser pour favoriser la convergence des contributions et la récipricité économique autour des communs
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://encommus.org" # the base hostname & protocol for your site
twitter_username: encommuns
github_username:  encommuns.github.io
logo: 
# Build settings
markdown: kramdown
