# Site settings

title: Livrables
email: contact@encommuns.org
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://encommus.org" # the base hostname & protocol for your site
twitter_username: encommuns
github_username:  encommuns.github.io
logo: 
# Build settings
markdown: kramdown
